/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#111418",
        "surface-dim": "#111418",
        "surface-bright": "#36393e",
        "surface-container-lowest": "#0b0e12",
        "surface-container-low": "#191c20",
        "surface-container": "#1d2024",
        "surface-container-high": "#272a2f",
        "surface-container-highest": "#32353a",
        "on-surface": "#e1e2e8",
        "on-surface-variant": "#bdc8d1",
        "inverse-surface": "#e1e2e8",
        "inverse-on-surface": "#2e3135",
        "outline": "#87929a",
        "outline-variant": "#3e484f",
        "surface-tint": "#7bd0ff",
        "primary": "#8ed5ff",
        "on-primary": "#00354a",
        "primary-container": "#38bdf8",
        "on-primary-container": "#004965",
        "inverse-primary": "#00668a",
        "secondary": "#4edea3",
        "on-secondary": "#003824",
        "secondary-container": "#00a572",
        "on-secondary-container": "#00311f",
        "tertiary": "#ffbcbf",
        "on-tertiary": "#67001b",
        "tertiary-container": "#ff929a",
        "on-tertiary-container": "#8c0028",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#c4e7ff",
        "primary-fixed-dim": "#7bd0ff",
        "on-primary-fixed": "#001e2c",
        "on-primary-fixed-variant": "#004c69",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-fixed": "#ffdadb",
        "tertiary-fixed-dim": "#ffb2b7",
        "on-tertiary-fixed": "#40000d",
        "on-tertiary-fixed-variant": "#92002a",
        "background": "#111418",
        "on-background": "#e1e2e8",
        "surface-variant": "#32353a",
        "status-critical": "#FF3D00",
        "stroke-subtle": "rgba(255, 255, 255, 0.08)",
        "surface-elevated": "#161B22",
        "surface-card": "#0D1117",
        "data-node-person": "#00E5FF",
        "status-success": "#00E676",
        "status-warning": "#FFB300",
        "data-node-event": "#FF4081"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sidebar-width": "280px",
        "margin-mobile": "16px",
        "inspector-width": "400px",
        "margin-desktop": "32px",
        "unit": "4px",
        "gutter": "16px",
        "space-lg": "1rem",
        "density-table-row": "1.75rem",
        "margin-console": "1rem",
        "space-xs": "0.25rem",
        "space-md": "0.75rem",
        "space-2xs": "0.125rem",
        "space-sm": "0.5rem",
        "space-2xl": "2rem",
        "space-xl": "1.5rem",
        "gutter-panel": "1px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "data-code": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-command": ["Inter", "sans-serif"],
        "body-compact": ["Inter", "sans-serif"],
        "telemetry-data-lg": ["JetBrains Mono", "monospace"],
        "body-default": ["Inter", "sans-serif"],
        "label-tactical": ["JetBrains Mono", "monospace"],
        "display-command-mobile": ["Inter", "sans-serif"],
        "telemetry-data-md": ["JetBrains Mono", "monospace"],
        "telemetry-data-sm": ["JetBrains Mono", "monospace"],
        "title-panel": ["Inter", "sans-serif"],
        "code-stream": ["JetBrains Mono", "monospace"],
        "headline-dossier": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "data-code": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "display-command": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-compact": ["12px", { "lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "400" }],
        "telemetry-data-lg": ["20px", { "lineHeight": "26px", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "body-default": ["13px", { "lineHeight": "19px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-tactical": ["10px", { "lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "display-command-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "telemetry-data-md": ["13px", { "lineHeight": "18px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "telemetry-data-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0em", "fontWeight": "400" }],
        "title-panel": ["15px", { "lineHeight": "22px", "letterSpacing": "-0.005em", "fontWeight": "500" }],
        "code-stream": ["11px", { "lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-dossier": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
