/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#e2e2e8",
        "tertiary": "#f1e9ff",
        "surface-container-high": "#282a2e",
        "outline-variant": "#3b494c",
        "status-critical": "#FF3D00",
        "on-tertiary-container": "#622be5",
        "on-primary-fixed": "#001f24",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "secondary-fixed": "#e0e0ff",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#bac9cc",
        "primary-fixed": "#9cf0ff",
        "primary-container": "#00e5ff",
        "inverse-primary": "#006875",
        "stroke-subtle": "rgba(255, 255, 255, 0.08)",
        "tertiary-fixed-dim": "#cdbdff",
        "outline": "#849396",
        "on-secondary": "#1b247f",
        "surface-bright": "#37393e",
        "surface-dim": "#111318",
        "surface": "#111318",
        "status-warning": "#FFB300",
        "on-secondary-container": "#a8afff",
        "inverse-surface": "#e2e2e8",
        "on-secondary-fixed-variant": "#343d96",
        "surface-elevated": "#161B22",
        "on-tertiary-fixed": "#20005f",
        "on-primary": "#00363d",
        "on-primary-fixed-variant": "#004f58",
        "surface-card": "#0D1117",
        "data-node-person": "#00E5FF",
        "status-success": "#00E676",
        "surface-container-low": "#1a1c20",
        "background": "#111318",
        "on-primary-container": "#00626e",
        "surface-variant": "#333539",
        "secondary": "#bdc2ff",
        "on-tertiary": "#370096",
        "surface-container": "#1e2024",
        "tertiary-container": "#d6c9ff",
        "primary-fixed-dim": "#00daf3",
        "inverse-on-surface": "#2f3035",
        "on-tertiary-fixed-variant": "#4f00d0",
        "on-secondary-fixed": "#000767",
        "primary": "#c3f5ff",
        "secondary-container": "#343d96",
        "surface-container-lowest": "#0c0e12",
        "on-background": "#e2e2e8",
        "secondary-fixed-dim": "#bdc2ff",
        "surface-container-highest": "#333539",
        "tertiary-fixed": "#e8deff",
        "surface-tint": "#00daf3",
        "data-node-event": "#FF4081"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sidebar-width": "280px",
        "margin-mobile": "16px",
        "inspector-width": "400px",
        "margin-desktop": "32px",
        "unit": "4px",
        "gutter": "16px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "data-code": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "data-code": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
